Add support for zipped unsorted MTX files
broadinstitute/scp-ingest-pipeline pull request #162
Opened 2020-10-30 14:37 UTC by knapii-developments

2020-10-30 16:28 UTC, bistline approved these changes
I'm assuming the reason you're actually unzipping the matrix is so that it can be sorted?  If so this looks good.

2020-11-02 16:28 UTC, eweitz requested changes
I'm glad this new support is getting refined!

I found a blocker:  see comment beginning "[This has a subtle bug](https://github.com/broadinstitute/scp-ingest-pipeline/pull/162#discussion_r516096159)".  I also suggested some readability improvements.

2020-11-02 16:31 UTC, eweitz commented on ingest/expression_files/mtx.py
> +        file_name = ntpath.split(file_path)[1][:-3]
This has a subtle bug: `file_name` retains a period.  The [robust approach you use elsewhere](https://github.com/broadinstitute/scp-ingest-pipeline/pull/162/files#diff-523e80ea0f210d08dda74bd7279f507ef450e6aa75d444aac8bee2f6bbed2895R95) seems preferable.

Bug demo:
```
wm10d-4e7:single_cell_portal_core eweitz$ python3
Python 3.7.7 (default, Mar 10 2020, 15:43:03) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ntpath
>>> file_path = '/path/to/file.txt'
>>> ntpath.split(file_path)[1][:-3]
'file.'
```

Applying your other, robust approach:

```suggestion
        file_name = os.path.basename(file_path)
        file_name = os.path.splitext(base)[0]
```

2020-11-03 20:12 UTC, knapii-developments commented on ingest/ingest_files.py
> +        if self.get_file_type(file_path)[1] == "gzip":
9b6af33

2020-11-03 20:13 UTC, knapii-developments commented on ingest/expression_files/mtx.py
> +        if IngestFiles.get_file_type(file_path)[1] == "gzip":
9b6af33

2020-11-03 20:21 UTC, knapii-developments commented on ingest/ingest_files.py
> +        if self.get_file_type(file_path)[1] == "gzip":
Tests for this 25e8ae7

2020-11-04 12:50 UTC, eweitz approved these changes

2020-11-04 14:01 UTC, merged