Store numerica arrays as group annotation types
broadinstitute/scp-ingest-pipeline pull request #205
Opened 2021-02-04 16:24 UTC by knapii-developments

2021-02-04 19:11 UTC, bistline requested changes
I have a concern that while these files will ingest, they will not visualize based off of this comment: **Notice how the stored 'values', as in production, are treated as normal numeric arrays.**

The entries found in `values` for group-based annotations are in two main places: determining whether or not a particular annotation can be visualized (between 2 & 200 unique values), and for initializing all of the Plotly trace entries when rendering any visualization.  If we are ingesting these files and marking them as "group" without doing anything else, then they will not appear in the "Annotation" dropdown menu for selecting different annotations to visualize.

We will either need to store the unique values - in which case everything will work as normal - or some other mechanism must be devised for visualizing these particular annotations.

2021-02-04 19:41 UTC, jlchang commented
> I have a concern that while these files will ingest, they will not visualize based off of this comment: **Notice how the stored 'values', as in production, are treated as normal numeric arrays.**
> 
> The entries found in `values` for group-based annotations are in two main places: determining whether or not a particular annotation can be visualized (between 2 & 200 unique values), and for initializing all of the Plotly trace entries when rendering any visualization. If we are ingesting these files and marking them as "group" without doing anything else, then they will not appear in the "Annotation" dropdown menu for selecting different annotations to visualize.
> 
> We will either need to store the unique values - in which case everything will work as normal - or some other mechanism must be devised for visualizing these particular annotations.

I'm surprised we'd store the values as a numeric array. I'd assume we would store them as an array of strings (specifically, strings that have numbers and zero or more small amount of pipes in the string). For [valid_array_v2.1.2.txt](https://github.com/broadinstitute/scp-ingest-pipeline/blob/development/tests/data/valid_array_v2.1.2.txt), I would expect the array of values in Mongo to be exactly what Eno saw when she looked in Mongo on Friday
<img width="795" alt="Screen Shot 2021-01-29 at 5 04 37 PM" src="https://user-images.githubusercontent.com/6005195/106946310-f26ab700-66f6-11eb-939b-2635bee63806.png">
(ie "values" : [ "12|2", "1", "24|2", "36|3|1", "0" ])

2021-02-04 20:00 UTC, bistline commented
> (ie "values" : [ "12|2", "1", "24|2", "36|3|1", "0" ])

Sorry - I'm proposing exactly that: storing the unique values as an array of strings, like you've shown.

2021-02-04 20:01 UTC, knapii-developments commented
> > (ie "values" : [ "12|2", "1", "24|2", "36|3|1", "0" ])
> 
> Sorry - I'm proposing exactly that: storing the unique values as an array of strings, like you've shown.

Just checking that we're all on the same page,  the model shown in the description is the cell metadata model and not the data array model.

2021-02-04 21:12 UTC, jlchang commented
> > > (ie "values" : [ "12|2", "1", "24|2", "36|3|1", "0" ])
> > 
> > 
> > Sorry - I'm proposing exactly that: storing the unique values as an array of strings, like you've shown.
> 
> Just checking that we're all on the same page, the model shown in the description is the cell metadata model and not the data array model.

Is there some way to re-word the opening PR description so future me doesn't mis-interpret again?

2021-02-04 21:18 UTC, bistline commented
How about this:

> Stored array-valued annotations that Mongo treated as “numeric” were plotted as NaN. To allow these annotations to be visualized in SCP, we should treat the array-based numeric data as a single string, and process the annotations as though they were regular group-based metadata entries (including storing all unique values).

2021-02-11 15:06 UTC, bistline approved these changes

2021-02-11 15:56 UTC, eweitz approved these changes
Looks good.  I suggested a typo fix and a maintainability refinement -- no blockers.

2021-02-11 15:56 UTC, eweitz commented on ingest/cell_metadata.py
> +
A comment here would help maintainability.

2021-03-02 16:44 UTC, devonbush approved these changes

2021-03-08 13:35 UTC, merged