Relaxing ontology label matching (SCP-3370)
broadinstitute/scp-ingest-pipeline pull request #211
Opened 2021-05-27 21:56 UTC by bistline

Currently, ingest pipeline enforces strict matching on all required ontology label columns in convention metadata files.  While this ensures a high degree of uniformity, it has the large downside of generating largely pointless errors when OLS updates an ontology label (such as recent changes to "10x" sequencing technology labels) and a user has not used the updated term in their metadata file.

This update relaxes this requirement to allow both case-insensitive matches, and any approved synonyms or related synonyms for a given ontology entry.  For example:

A user provides `10x 3' v2 sequencing` as the value for `library_preparation_protocol__ontology_label`, using the ontology ID of `EFO_0009899`.  The actual label according to the [EFO ontology](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0009899) is `10x 3' v2`, but `10x 3' v2 sequencing` is listed as an official synonym, as is `10X 3' v2`.  This value would be marked acceptable under these new conditions, whereas previously it would have thrown an error and caused the file to fail validation, and be deleted from the user's study.

TO TEST:
1. Pull this branch and run the installation instructions from the [README](https://github.com/broadinstitute/scp-ingest-pipeline#install)
2. Navigate to `ingest/validation`
3. Run `python3 validate_metadata.py ../../tests/data/annotation/metadata/convention/valid_no_array_synonyms_v2.0.0.txt`
4. Note there are no errors, only warnings
5. Validate script returned ok by checking `echo $?`, which will return `0`

This PR satisfies SCP-3370.

2021-06-02 20:00 UTC, eweitz requested changes
This will be a nice user quality-of-life improvement -- and for us implementers, too.  No more scrambling due to such trivial upstream changes!

With a few refinements to prevent maintainers from stumbling, I think this will be good to go.

2021-06-03 14:17 UTC, bistline commented on ingest/validation/validate_metadata.py
>          """Retrieve an individual term label from an ontology
94e8cae

2021-06-03 14:17 UTC, bistline commented on ingest/validation/validate_metadata.py
> +                label_lookup = labels_and_synonyms.get('label')
94e8cae

2021-06-03 14:17 UTC, bistline commented on ingest/validation/validate_metadata.py
> +            labels_and_synonyms = retriever.retrieve_ontology_term_labels_and_synonyms(
94e8cae

2021-06-03 14:17 UTC, bistline commented on ingest/validation/validate_metadata.py
> +    :param labels: cached ontology labels from retriever.retrieve_ontology_term_label
94e8cae

2021-06-03 14:18 UTC, bistline commented on ingest/validation/validate_metadata.py
> +                labels_and_synonyms = retriever.retrieve_ontology_term_labels_and_synonyms(
94e8cae

2021-06-03 14:18 UTC, bistline commented on ingest/validation/validate_metadata.py
> +                    matched_label_for_id = labels_and_synonyms.get("label")
94e8cae

2021-06-03 14:18 UTC, bistline commented on ingest/validation/validate_metadata.py
> +            label = labels_and_synonyms.get('label')
94e8cae

2021-06-03 14:18 UTC, bistline commented on ingest/validation/validate_metadata.py
> +                labels_and_synonyms = retriever.retrieve_ontology_term_labels_and_synonyms(
94e8cae

2021-06-03 14:22 UTC, eweitz approved these changes

2021-06-04 10:50 UTC, jlchang approved these changes
This is great, Jon. I'm so glad that we can allow synonyms in our validation. I'll find the right place in our documentation to indicate the newly allowed exception and also make a ticket to find the right place in the Alexandria documentation and send over a PR to update their docs so end users know they should operate on the IDs rather than the labels because labels can evolve over time.

2021-06-04 19:32 UTC, merged