improved variable scoping
broadinstitute/scp-ingest-pipeline pull request #248
Opened 2022-04-16 13:08 UTC by devonbush

2022-04-16 13:38 UTC, jlchang requested changes
Having `try:` above IngestPipeline object instantiation results in `NameError: name '__event_name' is not defined` because config isn't fully initialized ([more details](https://broadinstitute.slack.com/archives/CBEHTH601/p1650115317813179?thread_ts=1650107131.342889&cid=CBEHTH601))

Shifting the `try:` statement down one line should resolve the NameError.

Not entirely clear if it will yield the logging (Sentry or log files) we're hoping for, but it should get us closer...

2022-04-16 13:38 UTC, jlchang commented on ingest/ingest_pipeline.py
> +    config.init(
local testing shows this erroring out:
```
Traceback (most recent call last):  
  File "ingest_pipeline.py", line 614, in <module>  
    main()  
  File "ingest_pipeline.py", line 608, in main  
    MetricsService.log(config.get_parent_event_name(), config.get_metric_properties())  
  File "/Users/jlchang/Documents/GitHub/scp-ingest-pipeline/ingest/config.py", line 28, in get_parent_event_name  
    return __event_name  
NameError: name '__event_name' is not defined
```
Moving `try:` down one line so the IngestPipeline object is instantiated should resolve this error.

2022-04-19 14:12 UTC, eweitz approved these changes
Could you add a PR description, for some context?  

To my understanding, the intent here is to improve observability of unhandled errors in Mixpanel -- something like that seems like a more useful PR title, to help us recall what this PR did after it's no longer top-of-mind.

That said, code looks good!

2022-04-19 14:44 UTC, jlchang approved these changes
Confirmed that simulated error will result in stack trace to `log.txt`
confirmed Mixpanel logging of `ingest-pipeline:unhandled-exception:ingest` events

2022-04-19 14:45 UTC, merged